---

- name: Generate deploy vars file
  hosts: localhost
  gather_facts: false
  connection: local

  vars_files:
    - vars/aws/kafka_manager.yaml
    - vars/deploy/kafka_manager.yaml

  roles:
    - name: community/deploy_config